import { useState, useCallback } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { supabase } from "@/integrations/supabase/client";
import { solToLamports } from "@/lib/constants";
import { useToast } from "@/hooks/use-toast";
import { Upload, Copy, ExternalLink, Check } from "lucide-react";

const SchedulePage = () => {
  const navigate = useNavigate();
  const { toast } = useToast();

  const [form, setForm] = useState({
    tokenName: "",
    tokenSymbol: "",
    description: "",
    twitterUrl: "",
    telegramUrl: "",
    websiteUrl: "",
    launchDate: "",
    launchTime: "",
    minContribution: "",
    maxContribution: "",
    enableMaxContribution: false,
  });
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [imagePreview, setImagePreview] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [successData, setSuccessData] = useState<{ id: string; url: string } | null>(null);
  const [copied, setCopied] = useState(false);

  const update = (key: string, value: string | boolean) => {
    setForm((prev) => ({ ...prev, [key]: value }));
  };

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setImageFile(file);
      setImagePreview(URL.createObjectURL(file));
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      let imageUrl: string | null = null;

      if (imageFile) {
        const ext = imageFile.name.split(".").pop();
        const path = `${crypto.randomUUID()}.${ext}`;
        const { error: uploadError } = await supabase.storage
          .from("token-images")
          .upload(path, imageFile);
        if (uploadError) throw uploadError;
        const { data: urlData } = supabase.storage.from("token-images").getPublicUrl(path);
        imageUrl = urlData.publicUrl;
      }

      const launchDatetime = new Date(`${form.launchDate}T${form.launchTime}`).toISOString();

      // Placeholder escrow wallet — will be generated by edge function in production
      const escrowPublicKey = "placeholder_" + crypto.randomUUID();
      const escrowEncryptedKey = "placeholder_encrypted";

      const { data, error } = await supabase.from("launches").insert({
        token_name: form.tokenName,
        token_symbol: form.tokenSymbol.toUpperCase(),
        description: form.description || null,
        image_url: imageUrl,
        twitter_url: form.twitterUrl || null,
        telegram_url: form.telegramUrl || null,
        website_url: form.websiteUrl || null,
        launch_datetime: launchDatetime,
        min_contribution_lamports: solToLamports(parseFloat(form.minContribution)),
        max_contribution_lamports: form.enableMaxContribution
          ? solToLamports(parseFloat(form.maxContribution))
          : null,
        escrow_wallet_public_key: escrowPublicKey,
        escrow_wallet_encrypted_private_key: escrowEncryptedKey,
        created_by_wallet: "not_connected",
        status: "scheduled",
      }).select().single();

      if (error) throw error;

      const url = `${window.location.origin}/launch/${data.id}`;
      setSuccessData({ id: data.id, url });
    } catch (err: any) {
      toast({
        title: "Error",
        description: err.message || "Failed to schedule launch.",
        variant: "destructive",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  const copyLink = () => {
    if (successData) {
      navigator.clipboard.writeText(successData.url);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const tweetText = encodeURIComponent(
    `I just scheduled a Bags token launch on Erys. Get in before it goes live and earn fees forever.\n\n${successData?.url || ""}\n\nBuilt on @BagsApp`
  );

  if (successData) {
    return (
      <main className="min-h-screen">
        <div className="container mx-auto max-w-lg px-4 py-16">
          <div className="border border-primary/30 bg-card p-8 text-center space-y-6">
            <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-success/10">
              <Check className="h-8 w-8 text-success" />
            </div>
            <h2 className="text-2xl font-bold text-foreground">Launch Scheduled!</h2>
            <p className="text-sm text-muted-foreground">Share this link with your community.</p>

            <div className="flex items-center gap-2 rounded-sm border border-border bg-background p-3">
              <code className="flex-1 truncate text-xs text-primary">{successData.url}</code>
              <Button variant="outline" size="icon" className="h-8 w-8 flex-shrink-0" onClick={copyLink}>
                {copied ? <Check className="h-3.5 w-3.5 text-success" /> : <Copy className="h-3.5 w-3.5" />}
              </Button>
            </div>

            <a
              href={`https://twitter.com/intent/tweet?text=${tweetText}`}
              target="_blank"
              rel="noopener noreferrer"
            >
              <Button variant="outline" className="w-full gap-2 mt-2">
                <ExternalLink className="h-4 w-4" />
                Share on Twitter
              </Button>
            </a>

            <Button variant="ghost" className="w-full" onClick={() => navigate(`/launch/${successData.id}`)}>
              View Launch Page
            </Button>
          </div>
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen">
      <div className="container mx-auto max-w-xl px-4 py-12">
        <h1 className="text-2xl font-bold text-foreground md:text-3xl">Schedule a Bags Token Launch.</h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Your token will be launched exclusively on Bags.fm with community fee sharing built in from day one.
        </p>

        <form onSubmit={handleSubmit} className="mt-8 space-y-6">
          <div className="space-y-4 border border-border bg-card p-6">
            {/* Token Name */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label>Token Name</Label>
                <span className="text-[10px] text-muted-foreground">{form.tokenName.length}/32</span>
              </div>
              <Input
                maxLength={32}
                value={form.tokenName}
                onChange={(e) => update("tokenName", e.target.value)}
                placeholder="My Token"
                required
              />
            </div>

            {/* Token Symbol */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label>Token Symbol</Label>
                <span className="text-[10px] text-muted-foreground">{form.tokenSymbol.length}/10</span>
              </div>
              <Input
                maxLength={10}
                value={form.tokenSymbol}
                onChange={(e) => update("tokenSymbol", e.target.value.toUpperCase())}
                placeholder="TKN"
                className="font-mono uppercase"
                required
              />
            </div>

            {/* Description */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label>Description</Label>
                <span className="text-[10px] text-muted-foreground">{form.description.length}/1000</span>
              </div>
              <Textarea
                maxLength={1000}
                value={form.description}
                onChange={(e) => update("description", e.target.value)}
                placeholder="Describe your token..."
                rows={4}
              />
            </div>

            {/* Image upload */}
            <div className="space-y-2">
              <Label>Token Image</Label>
              <label className="flex cursor-pointer flex-col items-center justify-center rounded-sm border border-dashed border-border bg-background p-6 transition-colors hover:border-primary/30">
                {imagePreview ? (
                  <img src={imagePreview} alt="Preview" className="h-24 w-24 rounded-sm object-cover" />
                ) : (
                  <>
                    <Upload className="mb-2 h-6 w-6 text-muted-foreground" />
                    <span className="text-xs text-muted-foreground">Click or drag to upload</span>
                  </>
                )}
                <input type="file" accept="image/*" className="hidden" onChange={handleImageChange} />
              </label>
            </div>
          </div>

          {/* Social links */}
          <div className="space-y-4 border border-border bg-card p-6">
            <h3 className="text-sm font-semibold text-foreground">Social Links (optional)</h3>
            <Input
              value={form.twitterUrl}
              onChange={(e) => update("twitterUrl", e.target.value)}
              placeholder="Twitter URL"
            />
            <Input
              value={form.telegramUrl}
              onChange={(e) => update("telegramUrl", e.target.value)}
              placeholder="Telegram URL"
            />
            <Input
              value={form.websiteUrl}
              onChange={(e) => update("websiteUrl", e.target.value)}
              placeholder="Website URL"
            />
          </div>

          {/* Launch time */}
          <div className="space-y-4 border border-border bg-card p-6">
            <h3 className="text-sm font-semibold text-foreground">Launch Time</h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Date</Label>
                <Input
                  type="date"
                  value={form.launchDate}
                  onChange={(e) => update("launchDate", e.target.value)}
                  required
                />
              </div>
              <div className="space-y-2">
                <Label>Time</Label>
                <Input
                  type="time"
                  value={form.launchTime}
                  onChange={(e) => update("launchTime", e.target.value)}
                  required
                />
              </div>
            </div>
            <p className="text-[10px] text-muted-foreground">
              Times are in your local timezone ({Intl.DateTimeFormat().resolvedOptions().timeZone}).
            </p>
          </div>

          {/* Contributions */}
          <div className="space-y-4 border border-border bg-card p-6">
            <h3 className="text-sm font-semibold text-foreground">Contribution Limits</h3>
            <div className="space-y-2">
              <Label>Minimum Contribution (SOL)</Label>
              <Input
                type="number"
                step="0.01"
                min="0.01"
                value={form.minContribution}
                onChange={(e) => update("minContribution", e.target.value)}
                placeholder="0.1"
                className="font-mono"
                required
              />
            </div>
            <div className="flex items-center gap-3">
              <Switch
                checked={form.enableMaxContribution}
                onCheckedChange={(v) => update("enableMaxContribution", v)}
              />
              <Label>Enable maximum contribution per wallet</Label>
            </div>
            {form.enableMaxContribution && (
              <div className="space-y-2">
                <Label>Maximum Contribution (SOL)</Label>
                <Input
                  type="number"
                  step="0.01"
                  min="0.01"
                  value={form.maxContribution}
                  onChange={(e) => update("maxContribution", e.target.value)}
                  placeholder="10"
                  className="font-mono"
                  required
                />
              </div>
            )}
          </div>

          {/* Info box */}
          <div className="border-l-2 border-primary bg-muted p-4">
            <p className="text-xs leading-relaxed text-muted-foreground">
              When you schedule a launch a unique escrow wallet is generated for this launch. All contributor SOL is held there until your token launches automatically at the scheduled time.
            </p>
          </div>

          <Button type="submit" className="w-full" size="lg" disabled={isSubmitting}>
            {isSubmitting ? "Scheduling..." : "Schedule Launch"}
          </Button>
        </form>
      </div>
    </main>
  );
};

export default SchedulePage;
