// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cifdozolzbztuohtdavx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpZmRvem9semJ6dHVvaHRkYXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU4MDAzODMsImV4cCI6MjA5MTM3NjM4M30.2g-chNVNPqoj5ZQUCAlTniSlKgKPCEqZ7gRK5nLCyCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});